codecov:
  require_ci_to_pass: true
  token: 97303993-4333-465d-af94-52f8c862fe3c
fixes:
  - "before/test/*::after/app/*"
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
coverage:
  precision: 2
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        base: auto
        flags:
        - unittests
        target: auto
    project:
      default:
        base: auto
        flags:
        - unittests
        target: auto
github_checks:
  annotations: true
ignore:
- ^node_modules/.*
slack_app: true