version: "3.8"

services:

  server:
    container_name: server
    # depends_on:
    #   - mongodb
    #on build le server avec le dockerfile du dossier server
    build: ./
    restart: always
    env_file: .env
    ports:
      - $NODE_PORT:$NODE_PORT
      - 587:587
    # variable d'environment pour permettre de confirgurer l'acces du server à mongo
    environment:
      - MONGODB_URL=$MONGODB_URL
      - ENV_TYPE=$ENV_TYPE
      - DEV_URL=$DEV_URL
      - OUTLOOK_MAIL=$OUTLOOK_MAIL
      - OUTLOOK_PASS=$OUTLOOK_PASS
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    networks:
      - server
 
volumes:
  db:

networks:
  server:
    driver: bridge
