version: "1.0"
services:
  server:
    container_name: server

    #on build le server avec le dockerfile du dossier server
    build: ./server
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
